# Build worker image (VM template)
image:
  - Visual Studio 2022

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# branches to build
branches:
  only:
    - main

# scripts that run after cloning repository
install:
  - set QTDIR=C:\Qt\6.9.3\msvc2022_64
  - set PATH=%PATH%;C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin;%QTDIR%\bin;"C:\\Program Files (x86)\\Inno Setup 6";"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64"

build_script:
  - qmake6 LibkiPrintStation.pro
  - mingw32-make
  - dir release
  - copy release\LibkiPrintStation.exe deploy\windows\LibkiPrintStation.exe
  - cd deploy
  - ISCC.exe installer-wizard.iss

# defines what we can export from the build environment
artifacts:
  - path: 'deploy\Output\LibkiPrintStation.exe'
    name: 'Libki Print Station (Unstable) [$(APPVEYOR_REPO_COMMIT)]'

# deployment configuration, deploy to github releases
deploy:
  release: libki-print-station-unstable-v$(APPVEYOR_REPO_COMMIT)
  description: 'Libki Print Station (Unstable) [$(APPVEYOR_REPO_COMMIT)]'
  artifact: 'deploy\Output\LibkiPrintStation.exe'
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  draft: false
  prerelease: true
  force_update: true
  skip_tags: true
  on:
    branch: main
